version: '3.4'

services:
  bank_database_mvc:
    image: ${DOCKER_REGISTRY-}bankdatabasemvc
    build:
      context: .
      dockerfile: Bank_Database_MVC/Dockerfile
    container_name: bank_db_mvc
    depends_on:
      - database
      - cache

  database:
    image: mcr.microsoft.com/mssql/server
    container_name: bank_db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "P@ssw0rd"
    ports:
      - "1433:1433"

  cache:
    image: redis
    container_name: bank_db_cache
    ports:
      - "6379:6379"
